### ISSUE TITLE
Ogre fails to built ( when running "port install ros-hydro-rviz_plugin_tutorials fails" )

### ISSUE THREAD

**Issue by jf---** [kyonifer/ros-macports#12]
( I realize not all components of roc-macports are known to work, so this is more documenting the functional periphery of what is working right now )

issue seems Tk related:
_:debug:build couldn't open "/System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/tclIndex": no such file or directory_

sudo port install ros-hydro-rviz_plugin_tutorials
dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
Password:
--->  Computing dependencies for ros-hydro-rviz_plugin_tutorials
--->  Dependencies to be installed: ros-hydro-rviz ogre ros-hydro-image_geometry opencv ros-hydro-image_transport ros-hydro-message_filters ros-hydro-interactive_markers ros-hydro-tf ros-hydro-roswtf ros-hydro-tf2 ros-hydro-tf2_msgs ros-hydro-tf2_ros ros-hydro-tf2_py ros-hydro-visualization_msgs ros-hydro-laser_geometry ros-hydro-map_msgs ros-hydro-nav_msgs ros-hydro-media_export ros-hydro-resource_retriever yaml-cpp
--->  Building ogre
Error: org.macports.build for port ogre returned: command execution failed
Error: Failed to install ogre
Please see the log file for port ogre for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_ogre/ogre/main.log
Error: The following dependencies were not installed: ros-hydro-rviz ogre ros-hydro-image_geometry opencv ros-hydro-image_transport ros-hydro-message_filters ros-hydro-interactive_markers ros-hydro-tf ros-hydro-roswtf ros-hydro-tf2 ros-hydro-tf2_msgs ros-hydro-tf2_ros ros-hydro-tf2_py ros-hydro-visualization_msgs ros-hydro-laser_geometry ros-hydro-map_msgs ros-hydro-nav_msgs ros-hydro-media_export ros-hydro-resource_retriever yaml-cpp
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ros-hydro-rviz_plugin_tutorials failed

_/opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_ogre/ogre/main.log_ looks like this:

:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_ogre/ogre/work/ogre_src_v1-7-3" && /usr/bin/make -j8 -w all 
:info:build Exit code: 2
:error:build org.macports.build for port ogre returned: command execution failed
:debug:build Error code: CHILDSTATUS 82454 2
:debug:build Backtrace: command execution failed
    while executing
"system -nice 0 $fullcmdstring"
    ("eval" body line 1)
    invoked from within
"eval system $notty $nice \$fullcmdstring"
    invoked from within
"command_exec build"
    (procedure "portbuild::build_main" line 8)
    invoked from within
"$procedure $targetname"
:info:build Warning: targets not executed for ogre: org.macports.activate org.macports.build org.macports.destroot org.macports.install
:error:build Failed to install ogre
:debug:build couldn't open "/System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/tclIndex": no such file or directory
    while executing
"open [file join $dir tclIndex]"
:notice:build Please see the log file for port ogre for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_graphics_ogre/ogre/main.log

**Comment by jf---** [comment]
haven't tried yet:
http://www.ogre3d.org/tikiwiki/Installing+the+Ogre+SDK?tikiversion=Mac+OS+X

**Comment by kyonifer** [comment]
This is an issue with the upstream OGRE package in macports (there's a number of outstanding tickets, i.e. https://trac.macports.org/ticket/34502 https://trac.macports.org/ticket/37734 https://trac.macports.org/ticket/38624). One thing that might help is upgrading the outdated port to OGRE 1.8, which is mentioned there. I agree this would be a nice thing to have fixed. While we could write a parallel fixed OGRE port here in ros-macports temporarily, it would probably be better to contribute any fixes to the upstream port in macports to benefit all macports users (not just ros-macports users).

**Comment by kyonifer** [comment]
Latest (3afb25760adf367328704adc64855c2138a30d67, 6fdb17102922fb952d863cb0f5bd9c0047a209f3, and 9ea6cbb8eb1d640340bdacc6e0c3e6fb9263908d) contains a new ogre port called ros-ogre which fixes build issues on Mavericks+macports. This port resides in ros-macports for now, but I've notified upstream in the above ticket so hopefully they can merge a fix and we don't have to maintain a separate version long-term. I'm closing this issue since ogre seems to be functional. I did some minimal testing with rviz and some plugins which are working now. Please open separate issues for any other problems you encounter with the various gui related packages (i know rqt_image_view is still broken, due to https://github.com/ros-visualization/rqt_common_plugins/issues/206)
