### ISSUE TITLE
VTK is built with +tcltk +x11 rather than +qt4_mac

### ISSUE THREAD

**Issue by jf---** [kyonifer/ros-macports#13]
TCL and X11 preferred above Python and Cocoa, blasphemy...

--->  Installing ros-hydro-map_msgs @1.0.0_0
--->  Activating ros-hydro-map_msgs @1.0.0_0
--->  Cleaning ros-hydro-map_msgs
--->  Fetching archive for vtk5
--->  Attempting to fetch vtk5-5.10.1_0+tcltk+x11.darwin_12.x86_64.tbz2 from http://lil.fr.packages.macports.org/vtk5
--->  Attempting to fetch vtk5-5.10.1_0+tcltk+x11.darwin_12.x86_64.tbz2.rmd160 from http://lil.fr.packages.macports.org/vtk5
--->  Installing vtk5 @5.10.1_0+tcltk+x11
--->  Activating vtk5 @5.10.1_0+tcltk+x11
--->  Cleaning vtk5
--->  Fetching archive for libpcl
Error: org.macports.archivefetch for port libpcl returned: vtk5 must be installed with +qt4_mac.
Error: Failed to install libpcl
Please see the log file for port libpcl for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/main.log
Error: The following dependencies were not installed: ros-hydro-base_local_planner ros-hydro-costmap_2d ros-hydro-pcl_conversions libpcl ros-hydro-pcl_msgs ros-hydro-pcl_ros ros-hydro-nodelet_topic_tools ros-hydro-visualization_msgs ros-hydro-voxel_grid ros-hydro-nav_core ros-hydro-clear_costmap_recovery ros-hydro-move_base_msgs ros-hydro-navfn ros-hydro-rotate_recovery
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ros-hydro-move_base failed

**Comment by jf---** [comment]
`sudo port uninstall vtk5
sudo port install vtk5 +qt4_mac +python27`

That works out, next you have (try) to install libpcl explicitely, before trying to install ros-hydro-rqt_moveit
Somehow, otherwise PCL tries to built without having (any?) of its dependencies installed ( clearly something wrong with the port file, as if topologically not sorted )

when running `sudo port install libpcl` things grind to a halt with no explicit / clear error.
still, yet another level deeper into tarpit

:info:build /usr/bin/clang++  -pipe -Os -I/opt/local/include -arch x86_64   -DNDEBUG -arch x86_64 -dynamiclib -Wl,-headerpad_max_install_names  -L/opt/local/lib -Wl,-headerpad_max_install_names -arch x86_64  -compatibility_version 1.7.0 -current_version 1.7.1 -o ../lib/libpcl_visualization.1.7.1.dylib -install_name /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1/lib/libpcl_visualization.1.7.dylib CMakeFiles/pcl_visualization.dir/src/point_picking_event.cpp.o CMakeFiles/pcl_visualization.dir/src/interactor_style.cpp.o CMakeFiles/pcl_visualization.dir/src/point_cloud_handlers.cpp.o CMakeFiles/pcl_visualization.dir/src/pcl_visualizer.cpp.o CMakeFiles/pcl_visualization.dir/src/histogram_visualizer.cpp.o CMakeFiles/pcl_visualization.dir/src/common/common.cpp.o CMakeFiles/pcl_visualization.dir/src/common/io.cpp.o CMakeFiles/pcl_visualization.dir/src/common/shapes.cpp.o CMakeFiles/pcl_visualization.dir/src/common/ren_win_interact_map.cpp.o CMakeFiles/pcl_visualization.dir/src/cloud_viewer.cpp.o CMakeFiles/pcl_visualization.dir/src/image_viewer.cpp.o CMakeFiles/pcl_visualization.dir/src/window.cpp.o CMakeFiles/pcl_visualization.dir/src/range_image_visualizer.cpp.o CMakeFiles/pcl_visualization.dir/src/common/float_image_utils.cpp.o CMakeFiles/pcl_visualization.dir/src/vtk/pcl_image_canvas_source_2d.cpp.o CMakeFiles/pcl_visualization.dir/src/vtk/pcl_context_item.cpp.o CMakeFiles/pcl_visualization.dir/src/vtk/vtkVertexBufferObject.cxx.o CMakeFiles/pcl_visualization.dir/src/vtk/vtkVertexBufferObjectMapper.cxx.o CMakeFiles/pcl_visualization.dir/src/vtk/vtkRenderWindowInteractorFix.cpp.o CMakeFiles/pcl_visualization.dir/src/pcl_painter2D.cpp.o CMakeFiles/pcl_visualization.dir/src/pcl_plotter.cpp.o CMakeFiles/pcl_visualization.dir/include/pcl/visualization/vtk/vtkRenderWindowInteractorFix.mm.o  -L/opt/local/lib/vtk-5.10 /opt/local/lib/libboost_system-mt.dylib /opt/local/lib/libboost_filesystem-mt.dylib /opt/local/lib/libboost_thread-mt.dylib /opt/local/lib/libboost_date_time-mt.dylib /opt/local/lib/libboost_iostreams-mt.dylib -lm -framework Cocoa ../lib/libpcl_common.1.7.1.dylib ../lib/libpcl_io.1.7.1.dylib ../lib/libpcl_kdtree.1.7.1.dylib /opt/local/lib/vtk-5.10/libvtkCommon.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkWidgets.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkHybrid.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkCharts.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkFiltering.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkRendering.5.10.1.dylib -framework AGL -framework OpenGL ../lib/libpcl_io_ply.1.7.1.dylib /opt/local/lib/libpng.dylib /opt/local/lib/libusb-1.0.dylib /usr/lib/libOpenNI.dylib /opt/local/lib/libusb-1.0.dylib /usr/lib/libOpenNI.dylib /opt/local/lib/libpcap.dylib ../lib/libpcl_common.1.7.1.dylib /opt/local/lib/libboost_system-mt.dylib /opt/local/lib/libboost_filesystem-mt.dylib /opt/local/lib/libboost_thread-mt.dylib /opt/local/lib/libboost_date_time-mt.dylib /opt/local/lib/libboost_iostreams-mt.dylib /opt/local/lib/libflann_cpp.dylib /opt/local/lib/vtk-5.10/libvtkViews.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkInfovis.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkWidgets.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkHybrid.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkVolumeRendering.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkRendering.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkImaging.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkGraphics.5.10.1.dylib -lobjc /opt/local/lib/vtk-5.10/libvtkIO.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkFiltering.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtkCommon.5.10.1.dylib /opt/local/lib/vtk-5.10/libvtksys.5.10.1.dylib -lm -lm /opt/local/lib/libQtGui.dylib /opt/local/lib/libQtSql.dylib /opt/local/lib/libQtCore.dylib -framework OpenGL -Wl,-rpath,/opt/local/lib/vtk-5.10 
:info:build cd /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1/visualization && /opt/local/bin/cmake -E cmake_symlink_library ../lib/libpcl_visualization.1.7.1.dylib ../lib/libpcl_visualization.1.7.dylib ../lib/libpcl_visualization.dylib
:info:build make[2]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1'
:info:build /opt/local/bin/cmake -E cmake_progress_report /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1/CMakeFiles  93 94 95 96 97 98
:info:build [ 28%] Built target pcl_visualization
:info:build make[1]: Leaving directory`/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1'
:info:build make: **\* [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1'
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/work/pcl-1.7.1" && /usr/bin/make -j8 -w all 
:info:build Exit code: 2
:error:build org.macports.build for port libpcl returned: command execution failed
:debug:build Error code: CHILDSTATUS 78436 2
:debug:build Backtrace: command execution failed
    while executing
"system -nice 0 $fullcmdstring"
    ("eval" body line 1)
    invoked from within
"eval system $notty $nice \$fullcmdstring"
    invoked from within
"command_exec build"
    (procedure "portbuild::build_main" line 8)
    invoked from within
"$procedure $targetname"
:info:build Warning: targets not executed for libpcl: org.macports.activate org.macports.build org.macports.destroot org.macports.install
:notice:build Please see the log file for port libpcl for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_gis_libpcl/libpcl/main.log

**Comment by kyonifer** [comment]
Hello,
This is the same issue as the one mentioned in caveats at (http://wiki.ros.org/hydro/Installation/OSX/MacPorts/Repository). AFAIK there isn't a clean way to force a particular variant (see https://trac.macports.org/ticket/126). In general, we probably want to let the user choose his version of VTK, and the default builds correctly. We could possibly warn that the default will bring in x11, but this would come up with a lot of ports, such as graphviz, which all use X11 by default. 

Really this isn't an issue with ros-macports but with the ports in macports using questionable defaults. A lot of ports bring in X11 by default and trying to use macports without ever bringing in X11 is walking through a minefield. I don't think there's much we should do about this in the ros-macports bindings.

**Comment by jf---** [comment]
OK, though something like that is important to mention in the documentation.
What would be the right channel to document / relay this kind of info?
I know its more of a macports question, sorry...

**Comment by kyonifer** [comment]
I'll modify the wiki to discuss that it might be necessary for other ports than just opencv.
