### ISSUE TITLE
Catkin: make install broken

### ISSUE THREAD

**Issue by smits** [kyonifer/ros-macports#2]
Due to the applied patches to catkin a make install (which happens also during devel builds in case of catkin_make_isolated) will always want to install into the hard-coded DESTDIR.

I suggest we try to find a way to get the installed catkin behave normally.

**Comment by kyonifer** [comment]
Hello,

The latest catkin actually supports destdir (see ros/catkin#499, ros/catkin@8067802506d0b66926b665ee301ca6ce77ab3deb). Removing the patches and using the DESTDIR environment variable is probably the easiest way forward. 

I'm planning on rolling out a set of packages for hydro when I get some time which will do just that, but it could be done for groovy too if there's interest.
