### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chbang76** [kyonifer/ros-macports#4]
--->  Fetching distfiles for ros-groovy-desktop-full
Error: org.macports.fetch for port ros-groovy-desktop-full returned: Using initial elements from: http://packages.ros.org/web/rosinstall/generate/raw/groovy/desktop-full
ERROR in config: Invalid multiproject yaml format in [http://packages.ros.org/web/rosinstall/generate/raw/groovy/desktop-full]: mapping values are not allowed here
  in "<file>", line 14, column 20
Please see the log file for port ros-groovy-desktop-full for details:
    /opt/local/var/macports/logs/_Users_changhyunbang_ros-macports_devel_ros-groovy-desktop-full/ros-groovy-desktop-full/main.log
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ros-groovy-desktop-full failed

**Comment by kyonifer** [comment]
Looks like they updated/removed the rosinstall web service. Going to that URL gives a deprecated notice.

**Comment by kyonifer** [comment]
The new hydro ports use an entirely different build process, so this should not be an issue anymore. Please give the hydro packages a try and open a new ticket if you encounter any problems. 

Note that the new process generates a separate port for each ros package (with properly generated dependencies), so you will need to choose specific packages unlike the old groovy packages. I'll probably create meta packages like e.g. ros-hydro-desktop in the future, but for now installing ros-hydro-roslaunch might be a good start to get roscore and friends, and then install others as needed.
