### ISSUE TITLE
ros-log4cxx fails to build on Mavericks

### ISSUE THREAD

**Issue by fferri** [kyonifer/ros-macports#5]
--->  Computing dependencies for ros-hydro-roslaunch.......
--->  Dependencies to be installed: ros-hydro-rosout ros-hydro-roscpp ros-hydro-rosconsole ros-log4cxx ros-hydro-xmlrpcpp ros-hydro-rosparam
--->  Building ros-log4cxx
Making all in src
Making all in main
Making all in cpp
if /bin/sh ../../../libtool --tag=CXX --mode=compile /usr/bin/clang++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"log4cxx\" -DVERSION=\"0.10.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1  -I. -I. -I../../../src/main/include -I../../../src/main/include  -I/opt/local/include   -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/opt/local/include/apr-1   -I/opt/local/include/apr-1 -I/opt/local/include  -pipe -Os -arch x86_64 -MT simpledateformat.lo -MD -MP -MF ".deps/simpledateformat.Tpo" -c -o simpledateformat.lo simpledateformat.cpp; \
    then mv -f ".deps/simpledateformat.Tpo" ".deps/simpledateformat.Plo"; else rm -f ".deps/simpledateformat.Tpo"; exit 1; fi
 /usr/bin/clang++ -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"log4cxx\" -DVERSION=\"0.10.0\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -I. -I. -I../../../src/main/include -I../../../src/main/include -I/opt/local/include -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/opt/local/include/apr-1 -I/opt/local/include/apr-1 -I/opt/local/include -pipe -Os -arch x86_64 -MT simpledateformat.lo -MD -MP -MF .deps/simpledateformat.Tpo -c simpledateformat.cpp  -fno-common -DPIC -o .libs/simpledateformat.o
simpledateformat.cpp:598:24: error: out-of-line definition of 'addToken' does not match any declaration in 'log4cxx::helpers::SimpleDateFormat'
void SimpleDateFormat::addToken(const logchar spec, const int repeat, const std::locale \* locale,
                       ^~~~~~~~
../../../src/main/include/log4cxx/helpers/simpledateformat.h:82:84: note: type of 3rd parameter of member declaration does not match definition ('const std::locale _' vs 'const std::locale *' (aka 'const std::__1::locale *'))
                  static void addToken(const logchar spec, const int repeat, const std::locale_ locale, PatternTokenList& pattern);
                                                                                   ^
simpledateformat.cpp:706:24: error: out-of-line definition of 'parsePattern' does not match any declaration in 'log4cxx::helpers::SimpleDateFormat'
void SimpleDateFormat::parsePattern( const LogString & fmt, const std::locale \* locale,
                       ^~~~~~~~~~~~
../../../src/main/include/log4cxx/helpers/simpledateformat.h:83:73: note: type of 2nd parameter of member declaration does not match definition ('const std::locale _' vs 'const std::locale *' (aka 'const std::__1::locale *'))
                  static void parsePattern(const LogString& spec, const std::locale_ locale, PatternTokenList& pattern);
                                                                        ^
simpledateformat.cpp:746:19: error: out-of-line definition of 'SimpleDateFormat' does not match any declaration in 'log4cxx::helpers::SimpleDateFormat'
SimpleDateFormat::SimpleDateFormat( const LogString & fmt, const std::locale \* locale ) : timeZone( TimeZone::getDefault() )
                  ^~~~~~~~~~~~~~~~
../../../src/main/include/log4cxx/helpers/simpledateformat.h:56:68: note: type of 2nd parameter of member declaration does not match definition ('const std::locale _' vs 'const std::locale *' (aka 'const std::__1::locale *'))
                  SimpleDateFormat(const LogString& pattern, const std::locale_ locale);
                                                                   ^
3 errors generated.
make[3]: **\* [simpledateformat.lo] Error 1
make[2]: **\* [all-recursive] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all-recursive] Error 1
Command failed: cd /opt/local/var/macports/build/_Users_user_ros-macports_groovy_ros-log4cxx/ros-log4cxx/work/apache-log4cxx-0.10.0 && make
Exit code: 2
Error: org.macports.build for port ros-log4cxx returned: command execution failed
Warning: targets not executed for ros-log4cxx: org.macports.activate org.macports.build org.macports.destroot org.macports.install
Error: Failed to install ros-log4cxx
Please see the log file for port ros-log4cxx for details:
    /opt/local/var/macports/logs/_Users_user_ros-macports_groovy_ros-log4cxx/ros-log4cxx/main.log
Error: The following dependencies were not installed: ros-hydro-rosout ros-hydro-roscpp ros-hydro-rosconsole ros-log4cxx ros-hydro-xmlrpcpp ros-hydro-rosparam
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ros-hydro-roslaunch failed

**Comment by venabled** [comment]
Are you trying to build on 10.9 (Mavericks) with XCode 5 by any chance?

**Comment by fferri** [comment]
Yes, sorry for not mentioning that!

$ uname -srm
Darwin 13.0.0 x86_64

$ xcodebuild -version
Xcode 5.0.1
Build version 5A2053

$ clang --version
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix

**Comment by venabled** [comment]
I had to compile log4cxx with gcc4.8. @kyonifer and I will look at this afternoon.

**Comment by fferri** [comment]
I have gcc48 port installed. How do I use that for compiling this port?

(I tried `port select --set gcc mp-gcc48` without any luck)

EDIT: ok, using `port install ros-hydro-roslaunch configure.compiler=macports-gcc-4.8` seems to work

**Comment by kyonifer** [comment]
We'll have to look at the best way to make this work on ML/mavericks. I don't think MP allows conditional dependencies, so we might just have to bring in gcc4.8 on both.

**Comment by venabled** [comment]
This should be fixed now in 995a09b7c301589789d521b671c87cd336ead81a

Using macports-gcc-4.8 to compile the ports while building them correctly, links against libstdc++ by default, and I've not been able to get macports' gcc to use libc++. @kyonifer was showing that that path might not end up working anyway, so we should stick to trying to get the ros chain to compile using apple's compilers for now. This is related to #6 , and will fix part of the problem.

**Comment by venabled** [comment]
Also for completion, the patch was found from the homebrew guys: 

https://github.com/mxcl/homebrew/issues/23744

**Comment by fferri** [comment]
yup, I can confirm the last commit resolves this issue, and also #6
