### ISSUE TITLE
ros-hydro-xmlrpcpp fails to build on Mavericks w/ clang

### ISSUE THREAD

**Issue by fferri** [kyonifer/ros-macports#7]
however builds fine forcing gcc-4.8

$ uname -srm
Darwin 13.0.0 x86_64

$ xcodebuild -version
Xcode 5.0.1
Build version 5A2053

$ clang --version
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.0.0
Thread model: posix

**Comment by kyonifer** [comment]
Someone running mavericks, please confirm this fixes it (@venabled?)

**Comment by venabled** [comment]
This is another one where we might want to be careful with macports-gcc-4.8. I'm checking to see if it creates any libraries that we need to worry about.

**Comment by venabled** [comment]
Potentially fixed in 96617b4d7292558bdbe646953302ba6263d849c4

**Comment by venabled** [comment]
Guess i could pull request instead of pushing to master and then telling you about it :)

**Comment by kyonifer** [comment]
Going to close this as its working on my Mavericks system with the latest. If there are any linking issues, we'll open another issue.
