### ISSUE TITLE
ros-hydro-roscpp fails to build on Mavericks

### ISSUE THREAD

**Issue by fferri** [kyonifer/ros-macports#8]
--->  Building ros-hydro-roscpp
[  6%] [ 16%] Built target roscpp_generate_messages_lisp
[ 23%] Built target roscpp_generate_messages_py
Built target roscpp_generate_messages_cpp
[ 23%] [ 23%] Built target roscpp_gencpp
Built target roscpp_generate_messages
[ 25%] [ 26%] [ 28%] Building CXX object CMakeFiles/roscpp.dir/src/libros/service_publication.cpp.o
[ 30%] Building CXX object CMakeFiles/roscpp.dir/src/libros/publication.cpp.o
Building CXX object CMakeFiles/roscpp.dir/src/libros/connection_manager.cpp.o
Building CXX object CMakeFiles/roscpp.dir/src/libros/file_log.cpp.o
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/connection_manager.cpp:28:
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/include/ros/connection_manager.h:29:
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/include/ros/connection.h:41:
In file included from /opt/local/include/boost/signals.hpp:9:
/opt/local/include/boost/signal.hpp:17:4: warning: "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-W#warnings]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
   ^
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/publication.cpp:30:
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/include/ros/connection.h:41:
In file included from /opt/local/include/boost/signals.hpp:9:
/opt/local/include/boost/signal.hpp:17:4: warning: "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-W#warnings]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
   ^
[ 31%] Building CXX object CMakeFiles/roscpp.dir/src/libros/transport/transport_udp.cpp.o
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/publication.cpp:34:
/opt/local/include/std_msgs/Header.h:78:69: error: implicit instantiation of undefined template 'std::allocator<void>'
   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
                                                                    ^
/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/publication.cpp:173:22: note: in instantiation of template class 'std_msgs::Header_std::allocator<void >' requested here
    std_msgs::Header header;
                     ^
/opt/local/include/ros/message_forward.h:33:28: note: template is declared here
template<typename T> class allocator;
                           ^
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/publication.cpp:34:
/opt/local/include/std_msgs/Header.h:78:98: error: 'rebind' following the 'template' keyword does not refer to a template
   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
                                                                                                 ^~~~~~
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/service_publication.cpp:37:
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/include/ros/connection.h:41:
In file included from /opt/local/include/boost/signals.hpp:9:
/opt/local/include/boost/signal.hpp:17:4: warning: "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING." [-W#warnings]
 #  warning                  "Boost.Signals is no longer being maintained and is now deprecated. Please switch to Boost.Signals2. To disable this warning message, define BOOST_SIGNALS_NO_DEPRECATION_WARNING."
   ^
1 warning and 2 errors generated.
make[2]: **\* [CMakeFiles/roscpp.dir/src/libros/publication.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/service_publication.cpp:42:
/opt/local/include/std_msgs/String.h:68:69: error: implicit instantiation of undefined template 'std::allocator<void>'
   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
                                                                    ^
/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/service_publication.cpp:139:24: note: in instantiation of template class 'std_msgs::String_std::allocator<void >' requested here
      std_msgs::String error_string;
                       ^
/opt/local/include/ros/message_forward.h:33:28: note: template is declared here
template<typename T> class allocator;
                           ^
In file included from /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/src/libros/service_publication.cpp:42:
/opt/local/include/std_msgs/String.h:68:98: error: 'rebind' following the 'template' keyword does not refer to a template
   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
                                                                                                 ^~~~~~
1 warning generated.
1 warning and 2 errors generated.
make[2]: **\* [CMakeFiles/roscpp.dir/src/libros/service_publication.cpp.o] Error 1
make[1]: **\* [CMakeFiles/roscpp.dir/all] Error 2
make: **\* [all] Error 2
Base path: /Users/user/ros-macports/hydro/ros-hydro-roscpp
Source space: /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0
Build space: /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated
Devel space: /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated
Install space: /opt/local
Additional CMake Arguments: -DCMAKE_SKIP_RPATH:BOOL=OFF -DCMAKE_INSTALL_NAME_DIR:STRING=/opt/local/lib -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON -DSETUPTOOLS_DEB_LAYOUT=OFF -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7

```
~~  traversing 1 packages in topological order:
~~  - roscpp
```

==> Processing catkin package: 'roscpp'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp' with '_CATKIN_SETUP_DIR=/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot/opt/local'
==> make -j4 -l4 in '/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp'
<== Failed to process package 'roscpp':
  Command 'make -j4 -l4' returned non-zero exit status 2

Reproduce this error by running:
==> cd /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated/roscpp && make -j4 -l4

Command failed, exiting.
Command failed: DESTDIR=/opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/destroot /opt/local/bin/catkin_make_isolated  --source /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0  --build /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/build_isolated  --devel /opt/local/var/macports/build/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/work/ros_comm-release-release-hydro-roscpp-1.9.50-0/devel_isolated  -DCMAKE_SKIP_RPATH:BOOL=OFF  -DCMAKE_INSTALL_NAME_DIR:STRING=/opt/local/lib  -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON  -DSETUPTOOLS_DEB_LAYOUT=OFF  -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7  --install-space=/opt/local  --install
Exit code: 1
Error: org.macports.build for port ros-hydro-roscpp returned: command execution failed
Warning: targets not executed for ros-hydro-roscpp: org.macports.activate org.macports.build org.macports.destroot org.macports.install
Error: Failed to install ros-hydro-roscpp
Please see the log file for port ros-hydro-roscpp for details:
    /opt/local/var/macports/logs/_Users_user_ros-macports_hydro_ros-hydro-roscpp/ros-hydro-roscpp/main.log
Error: The following dependencies were not installed: ros-hydro-rosout ros-hydro-roscpp
To report a bug, follow the instructions in the guide:
    http://guide.macports.org/#project.tickets
Error: Processing of port ros-hydro-roslaunch failed

**Comment by kyonifer** [comment]
This issue is fixed by 67627ad78ade49ee8aa620f1b722b0e34045db5b. Please use the latest master and make sure you reinstall roscpp_traits if you had it installed before this commit. 

At some point we need to make the port generation process add/update revision numbers, so changes to ports like this will increment the revision number and force macports to upgrade the outdated port. Doing a blanket revision update would not work, but manually updating revisions is a (not pleasant) option.

**Comment by fferri** [comment]
I confirm rebuilding roscpp_traits fixed this issue. Thank you :-)

**Comment by kyonifer** [comment]
No problem. Thanks for the help testing out ports! The only thing I know of that's broken atm is the visualization stuff, although there's a lot of ROS I don't personally use so there's likely to be other issues.
